### ISSUE TITLE
오탈자 수정 요청

### ISSUE THREAD

**Issue by dev-hikun** [ssi02014/Front-Interview#1]
안녕하세요, 해당 Repo를 재밌게 보았습니다.
보던 와중 [오탈자](https://github.com/ssi02014/Front-Interview/blame/master/Note/Frontend-Overall/browser-rendering-process.md#L15)가 있어서 해당 이슈를 작성해드립니다.

감사합니다.

**Comment by ssi02014** [comment]
감사합니다 수정하고 반영하겠습니다😃😃
