### ISSUE TITLE
(수정요청) iterable/iterator, generator 페이지 주소

### ISSUE THREAD

**Issue by tada-js** [ssi02014/Front-Interview#2]
`README.md`에는 [iterator-generator.md](https://github.com/ssi02014/Front-Interview/blob/master/Note/JavaScript/iterator-generator.md)로 연결되어 있어 404 페이지로 연결 됩니다.  [iterator_generator.md](https://github.com/ssi02014/Front-Interview/blob/master/Note/JavaScript/iterator_generator.md)로 수정해 주시면 감사하겠습니다! 😀

그리고, 너무 좋은 정보를 공유해 주셔서 감사드립니다!🎶

**Comment by ssi02014** [comment]
수정하였습니다 감사드립니다 🙇‍♂️
